database:
  batch:
    size: 10
    timeout: 1000
kafka:
  bootstrapAddress: localhost:9092
  topic:
    name: topicName1
    partitions: 2
  group1:
    name: group1
  group2:
    name: group2
  groups:
    number: 2
spring:
  datasource:
    platform: h2
  jpa:
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
#        generate_statistics: true
        jdbc:
          batch_size: 10
          order_inserts: true
      javax:
        persistence:
          validation:
            mode: none
