database:
  batch:
    size: 10
    timeout: 5000
kafka:
  bootstrapAddress: localhost:9092
  topic:
    name: topicName1
    partitions: 1
spring:
  datasource:
    platform: h2
  jpa:
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
#        generate_statistics: true
        jdbc:
          batch_size: 10
          order_inserts: true
